# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 2

[launcher]
author = gal@reco.ai
version = 2.0.0
description = Reco is the solution trusted by modern enterprises to secure SaaS AI, applications, and agents. Our SaaS & AI Security platform provides complete visibility and control across your entire SaaS ecosystem — from core SaaS applications to the latest AI agents — enabling security teams to keep pace with the speed of AI adoption while maintaining airtight security and reducing risk.

[ui]
is_visible = 1
label = Reco Addon
docs_section_override = AddOns:released

[id]
name = TA-reco

[package]
id = TA-reco
check_for_updates = false

[triggers]
reload.addon_builder = simple
reload.ta_reco_account = simple
reload.ta_reco_settings = simple
reload.passwords = simple
