[reco_alerts]
python.version = python3
python.required = 3.13
interval = 30
index = default
limit = 0
alert_status = 1
sourcetype = recoAlerts
start_by_shell = false

[reco_posture]
python.version = python3
python.required = 3.13
interval = 3600
index = default
status = 5
limit = 0
sourcetype = reco-posture
start_by_shell = false

[reco_identities]
python.version = python3
python.required = 3.13
interval = 43200
index = default
limit = 0
sourcetype = recoIdentities
start_by_shell = false

[reco_discovery]
python.version = python3
python.required = 3.13
interval = 43200
index = default
limit = 0
sourcetype = recoDiscovery
start_by_shell = false

[reco_system_logs]
python.version = python3
python.required = 3.13
interval = 30
index = default
limit = 0
sourcetype = recoSystemLogs
start_by_shell = false

[reco_accounts]
python.version = python3
python.required = 3.13
interval = 43200
index = default
limit = 0
sourcetype = recoAccounts
start_by_shell = false
